### ISSUE TITLE
Using any float-like type for the field

### ISSUE THREAD

**Issue by benruijl** [convexbrain/Totsu#20]
I'd like to use Totsu over any `num_traits::Float` type, like `f128` floats or perhaps even dual numbers. Is this possible?

**Comment by convexbrain** [comment]
Hi benruijl,

It's possible to make `Mat` generic using `num_traits::Float`, but its implementation will take a little time, I think. Not to make it generic but to use just `f128`, modifying `FP`, `FP_EPSILON` and `FP_MINPOS` in `matgen.rs` to those of `f128` maybe works.

As for dual numbers, you need to re-write an optimization problem by using dual numbers' element-wise real number vectors and matrices. It's because the base algorithm I used is based on $R^n$.

**Comment by convexbrain** [comment]
At version https://github.com/convexbrain/Totsu/releases/tag/rust_conic_v0.6.0, num::Float is employed overall.
